# Generated by Django 4.0.2 on 2022-02-13 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancion',
            name='cast',
        ),
    ]
