# Generated by Django 3.2.11 on 2022-03-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canciones', '0002_auto_20220314_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=250, verbose_name='rank')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('artist', models.CharField(max_length=250, verbose_name='artist')),
                ('peak', models.CharField(max_length=250, verbose_name='peak')),
                ('weeks', models.CharField(max_length=250, verbose_name='weeks')),
            ],
        ),
        migrations.DeleteModel(
            name='Cancion2',
        ),
    ]
