# Generated by Django 3.2.11 on 2022-03-12 16:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ViajesPage',
            new_name='ViajesIndexPage',
        ),
    ]
