# Generated by Django 3.2.11 on 2022-03-12 17:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viajes', '0002_rename_viajespage_viajesindexpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ViajesIndexPage',
            new_name='ViajesPage',
        ),
        migrations.DeleteModel(
            name='Viaje',
        ),
    ]
